// Mots du Codenames (français). 25 sont tirés au hasard à chaque partie.
// Pour en ajouter : un mot de plus dans la liste.
const WORDS: string[] = [
  'Abeille', 'Aéroport', 'Agent', 'Aiguille', 'Aile', 'Alarme', 'Alien', 'Amour', 'Ange', 'Anneau',
  'Antenne', 'Araignée', 'Arbre', 'Arc', 'Argent', 'Armée', 'Armure', 'Artiste', 'Astronaute', 'Avion',
  'Avocat', 'Bague', 'Baie', 'Balance', 'Balcon', 'Baleine', 'Ballon', 'Banane', 'Banc', 'Bande',
  'Banque', 'Barbe', 'Barre', 'Bateau', 'Bâton', 'Batterie', 'Bébé', 'Berger', 'Béton', 'Bibliothèque',
  'Bière', 'Bijou', 'Billet', 'Biscuit', 'Blé', 'Bleu', 'Bœuf', 'Boîte', 'Bombe', 'Bonnet',
  'Botte', 'Bouche', 'Boucher', 'Bouchon', 'Boule', 'Boussole', 'Bouteille', 'Branche', 'Bras', 'Brique',
  'Brosse', 'Brouillard', 'Bruit', 'Buisson', 'Bureau', 'Bus', 'Cabane', 'Cadeau', 'Café', 'Cage',
  'Calendrier', 'Caméra', 'Camion', 'Camp', 'Canal', 'Canard', 'Cancer', 'Cap', 'Capitaine', 'Carotte',
  'Carré', 'Carte', 'Casque', 'Casino', 'Casserole', 'Cave', 'Ceinture', 'Cendre', 'Cerf', 'Cerise',
  'Chaise', 'Chambre', 'Champagne', 'Champion', 'Chance', 'Change', 'Chanson', 'Chapeau', 'Charbon', 'Chariot',
  'Chasse', 'Chat', 'Château', 'Chaussure', 'Chef', 'Chemin', 'Cheminée', 'Chemise', 'Chêne', 'Cheval',
  'Cheveu', 'Chèvre', 'Chien', 'Chimie', 'Chocolat', 'Cible', 'Ciel', 'Cigare', 'Cinéma', 'Cirque',
  'Citron', 'Clavier', 'Clé', 'Cloche', 'Clou', 'Clown', 'Club', 'Cochon', 'Code', 'Cœur',
  'Coffre', 'Colle', 'Collier', 'Colline', 'Colonne', 'Comète', 'Concert', 'Confiture', 'Congé', 'Copie',
  'Coq', 'Corde', 'Corps', 'Costume', 'Côte', 'Coton', 'Couche', 'Coude', 'Couleur', 'Coupe',
  'Cour', 'Courant', 'Couronne', 'Course', 'Couteau', 'Couverture', 'Crabe', 'Craie', 'Crème', 'Crique',
  'Crocodile', 'Croix', 'Cuisine', 'Cuivre', 'Cygne', 'Dame', 'Danse', 'Dauphin', 'Dé', 'Désert',
  'Dessert', 'Détective', 'Diamant', 'Dinosaure', 'Docteur', 'Doigt', 'Dragon', 'Drapeau', 'Droit', 'Dune',
  'Eau', 'Échelle', 'École', 'Éclair', 'Éclipse', 'Écran', 'Écureuil', 'Église', 'Éléphant',
  'Empire', 'Enfant', 'Encre', 'Énergie', 'Épée', 'Épice', 'Éponge', 'Équipe', 'Escalier', 'Espace',
  'Espion', 'Essence', 'Étage', 'Étoile', 'Étudiant', 'Éventail', 'Examen', 'Fabrique', 'Face', 'Fantôme',
  'Farine', 'Fée', 'Fenêtre', 'Fer', 'Ferme', 'Feu', 'Feuille', 'Fièvre', 'Figure', 'Filet',
  'Fille', 'Film', 'Fleur', 'Fleuve', 'Flûte', 'Foire', 'Foot', 'Force', 'Forêt', 'Forge',
  'Fort', 'Fortune', 'Fouet', 'Foudre', 'Four', 'Fourmi', 'Fraise', 'Frère', 'Frigo', 'Fromage',
  'Front', 'Fruit', 'Fumée', 'Fusée', 'Fusil', 'Gâteau', 'Gauche', 'Gaz', 'Géant', 'Genou',
  'Gland', 'Glace', 'Globe', 'Gomme', 'Gorge', 'Gorille', 'Goutte', 'Grain', 'Graine', 'Graisse',
  'Grenade', 'Grenouille', 'Griffe', 'Grille', 'Grotte', 'Guerre', 'Guide', 'Guitare', 'Hache', 'Hall',
  'Hamster', 'Harpe', 'Hélice', 'Hélicoptère', 'Herbe', 'Héros', 'Hibou', 'Hiver', 'Homme', 'Hôpital',
  'Horloge', 'Hôtel', 'Huile', 'Huître', 'Île', 'Image', 'Impôt', 'Indien', 'Insecte', 'Internet',
  'Invention', 'Ivoire', 'Jambe', 'Jambon', 'Jardin', 'Jaune', 'Jeu', 'Journal', 'Jungle', 'Jupe',
  'Jury', 'Jus', 'Kangourou', 'Karaté', 'Kilo', 'Kiosque', 'Koala', 'Laboratoire', 'Lac', 'Laine',
  'Lait', 'Lame', 'Lampe', 'Lance', 'Langue', 'Lapin', 'Laser', 'Lavabo', 'Légume', 'Lettre',
  'Lèvre', 'Licorne', 'Lien', 'Lièvre', 'Ligne', 'Limite', 'Limonade', 'Lion', 'Liquide',
  'Lit', 'Livre', 'Locomotive', 'Loge', 'Loi', 'Loup', 'Lourd', 'Lumière', 'Lune', 'Lunettes',
  'Luxe', 'Lynx', 'Machine', 'Magasin', 'Magicien', 'Main', 'Maire', 'Maison', 'Malle', 'Manche',
  'Manège', 'Manteau', 'Marais', 'Marbre', 'Marché', 'Mariage', 'Marin', 'Marque', 'Marteau', 'Masque',
  'Matin', 'Médaille', 'Médecin', 'Mer', 'Mère', 'Mérite', 'Métal', 'Mètre', 'Métro', 'Meuble',
  'Micro', 'Miel', 'Mine', 'Ministre', 'Miroir', 'Mode', 'Moine', 'Monde', 'Monnaie', 'Monstre',
  'Montagne', 'Montre', 'Moquette', 'Mort', 'Mot', 'Moteur', 'Moto', 'Mouche', 'Mouton', 'Moulin',
  'Mur', 'Muscle', 'Musée', 'Musique', 'Nage', 'Nain', 'Nappe', 'Navire', 'Neige', 'Nerf',
  'Nez', 'Nid', 'Noël', 'Noir', 'Noix', 'Nombre', 'Nord', 'Note', 'Nuage', 'Nuit',
  'Océan', 'Œil', 'Œuf', 'Oie', 'Oignon', 'Oiseau', 'Ombre', 'Onde', 'Opéra', 'Or',
  'Orage', 'Orange', 'Ordinateur', 'Oreille', 'Os', 'Ours', 'Outil', 'Ouvrier', 'Page', 'Pain',
  'Paix', 'Palais', 'Palme', 'Pantalon', 'Papier', 'Papillon', 'Paquet', 'Parachute', 'Parc', 'Parfum',
  'Parking', 'Parole', 'Passeport', 'Pâte', 'Patin', 'Patrouille', 'Patron', 'Paupière', 'Peau', 'Pêche',
  'Peigne', 'Peintre', 'Pelle', 'Pendule', 'Pensée', 'Perle', 'Père', 'Perroquet', 'Personne', 'Pétrole',
  'Phare', 'Photo', 'Piano', 'Pied', 'Pierre', 'Pigeon', 'Pilote', 'Pince', 'Pingouin', 'Pipe',
  'Piquet', 'Pirate', 'Piscine', 'Piste', 'Pistolet', 'Pizza', 'Place', 'Plage', 'Plan', 'Planche',
  'Plante', 'Plat', 'Plateau', 'Plomb', 'Plongeur', 'Pluie', 'Plume', 'Poche', 'Poème', 'Poids',
  'Poignet', 'Poil', 'Point', 'Poire', 'Poisson', 'Poivre', 'Police', 'Pomme', 'Pompe', 'Pompier',
  'Pont', 'Porc', 'Port', 'Porte', 'Poste', 'Pot', 'Poule', 'Poulet', 'Poumon', 'Poupée',
  'Pouvoir', 'Prairie', 'Prince', 'Princesse', 'Prison', 'Prix', 'Prune', 'Puce', 'Puits', 'Pyramide',
  'Quai', 'Quartier', 'Queue', 'Radio', 'Raie', 'Raisin', 'Rang', 'Raquette',
  'Rat', 'Rayon', 'Reine', 'Remède', 'Renard', 'Requin', 'Réseau', 'Reste', 'Rêve', 'Rhum',
  'Rideau', 'Rivière', 'Riz', 'Robe', 'Robinet', 'Robot', 'Roche', 'Rocher', 'Roi', 'Romain',
  'Rond', 'Rose', 'Roue', 'Rouge', 'Route', 'Ruban', 'Rue', 'Ruine', 'Sable', 'Sac',
  'Sage', 'Saison', 'Salade', 'Sale', 'Salle', 'Salon', 'Sang', 'Santé', 'Sauce', 'Saut',
  'Savon', 'Scène', 'Science', 'Scie', 'Scorpion', 'Seau', 'Sel', 'Sentier', 'Serpent', 'Serre',
  'Serviette', 'Siège', 'Signe', 'Silence', 'Singe', 'Sirène', 'Ski', 'Soie', 'Soldat', 'Soleil',
  'Sommet', 'Son', 'Sorcière', 'Souris', 'Source', 'Spectacle', 'Sport', 'Station', 'Statue', 'Studio',
  'Sucre', 'Sud', 'Supermarché', 'Surf', 'Table', 'Tableau', 'Tabouret', 'Taille', 'Talon',
  'Tambour', 'Tank', 'Tapis', 'Tasse', 'Taupe', 'Taureau', 'Taxi', 'Télé', 'Téléphone', 'Télescope',
  'Tempête', 'Temps', 'Tennis', 'Tente', 'Terre', 'Tête', 'Thé', 'Théâtre', 'Ticket', 'Tigre',
  'Timbre', 'Tir', 'Titre', 'Toile', 'Toit', 'Tomate', 'Tombe', 'Tonneau', 'Tonnerre',
  'Tortue', 'Touche', 'Tour', 'Tournesol', 'Train', 'Trait', 'Transport', 'Travail', 'Trèfle',
  'Tribu', 'Trompette', 'Trône', 'Trou', 'Tube', 'Tuile', 'Tunnel', 'Tuyau', 'Union',
  'Univers', 'Usine', 'Vache', 'Vague', 'Vaisseau', 'Valise', 'Vallée', 'Vampire', 'Veau', 'Vélo',
  'Vent', 'Ver', 'Verre', 'Vert', 'Veste', 'Viande', 'Vidéo', 'Vigne', 'Village',
  'Ville', 'Vin', 'Violon', 'Virage', 'Vis', 'Visage', 'Visite', 'Voile', 'Voiture', 'Voix',
  'Vol', 'Volcan', 'Voleur', 'Voyage', 'Zèbre', 'Zéro', 'Zone', 'Zoo', 'Alpes', 'Amazonie',
  'Antarctique', 'Arctique', 'Atlantide', 'Berlin', 'Bretagne', 'Brésil', 'Canada', 'Chine',
  'Corse', 'Cuba', 'Égypte', 'Espagne', 'États-Unis', 'Europe', 'France', 'Grèce', 'Inde', 'Irlande',
  'Islande', 'Italie', 'Japon', 'Londres', 'Madrid', 'Mexique', 'Moscou', 'Norvège', 'Paris', 'Pérou',
  'Pologne', 'Rome', 'Russie', 'Sahara', 'Sibérie', 'Suède', 'Suisse', 'Tokyo', 'Vénus', 'Mars',
  'Mercure', 'Jupiter', 'Saturne', 'Pluton', 'Neptune', 'Orient', 'Occident', 'Napoléon', 'Merlin',
  'Robin', 'Zorro', 'Dracula', 'Frankenstein', 'Aladin', 'Cendrillon', 'Pinocchio', 'Hercule', 'Achille', 'Atlas',
  'Cupidon', 'Excalibur', 'Pégase', 'Titan', 'Odyssée', 'Olympe', 'Sphinx', 'Pharaon', 'Viking', 'Samouraï',
  'Ninja', 'Cow-boy', 'Chevalier', 'Gladiateur', 'Mousquetaire', 'Pile', 'Pic', 'Clavecin', 'Bourse', 'Bouée',
  'Bulle', 'Calcul', 'Câble', 'Cadre', 'Chaîne', 'Charge', 'Cuir', 'Digue', 'Dos', 'Ferry',
  'Fil', 'Forme', 'Fosse', 'Gamme', 'Gant', 'Glissade', 'Ligue', 'Moule', 'Noeud',
  'Noyau', 'Pièce', 'Pioche', 'Pique', 'Pôle', 'Prise', 'Rouleau', 'Sceau', 'Tige', 'Trompe',
  'Vase',
];

const pickWords = (n = 25): string[] => {
  const bag = [...WORDS];
  const out: string[] = [];
  while (out.length < n && bag.length) out.push(bag.splice(Math.floor(Math.random() * bag.length), 1)[0]);
  return out;
};

export { WORDS, pickWords };
