// Cartes « thème » du Top Ten : [thème, ce que vaut 1, ce que vaut 100].
// Pour en ajouter : une ligne de plus dans CARDS.
export type TenTheme = { t: string; lo: string; hi: string };

const CARDS: [string, string, string][] = [
  ['Un animal', 'inoffensif', 'dangereux'],
  ['Un animal', 'minuscule', 'gigantesque'],
  ['Un animal', 'ennuyeux', 'fascinant'],
  ['Un métier', 'facile', 'très dur'],
  ['Un métier', 'mal payé', 'très bien payé'],
  ['Un métier', 'ennuyeux', 'passionnant'],
  ['Un plat', 'léger', 'très copieux'],
  ['Un plat', 'dégoûtant', 'délicieux'],
  ['Un plat', 'pas cher', 'luxueux'],
  ['Un aliment', 'pas épicé', 'qui brûle la langue'],
  ['Une boisson', 'sans alcool', 'très forte'],
  ['Un film', 'nul', 'chef-d\'œuvre'],
  ['Un film', 'pas effrayant', 'terrifiant'],
  ['Un film', 'qui fait rire', 'qui fait pleurer'],
  ['Un personnage de dessin animé', 'gentil', 'méchant'],
  ['Un super-héros', 'inutile', 'surpuissant'],
  ['Un super-pouvoir', 'inutile', 'surpuissant'],
  ['Un objet', 'inutile', 'indispensable'],
  ['Un objet du quotidien', 'pas cher', 'très cher'],
  ['Un cadeau', 'nul', 'génial'],
  ['Un cadeau', 'pas cher', 'hors de prix'],
  ['Une activité', 'reposante', 'épuisante'],
  ['Une activité', 'qu\'on fait seul', 'qu\'on fait en grand groupe'],
  ['Un sport', 'peu physique', 'très physique'],
  ['Un sport', 'ennuyeux à regarder', 'spectaculaire'],
  ['Un sport', 'sans danger', 'très dangereux'],
  ['Un endroit pour des vacances', 'sans intérêt', 'paradisiaque'],
  ['Un endroit', 'calme', 'bruyant'],
  ['Une destination', 'proche', 'très lointaine'],
  ['Un pays', 'où on ne veut pas vivre', 'où on rêve de vivre'],
  ['Une ville', 'moche', 'magnifique'],
  ['Un moyen de transport', 'lent', 'rapide'],
  ['Un moyen de transport', 'sûr', 'risqué'],
  ['Une chose qui fait peur', 'pas du tout', 'panique totale'],
  ['Une peur', 'ridicule', 'tout à fait légitime'],
  ['Une excuse pour être en retard', 'crédible', 'absurde'],
  ['Une excuse pour annuler une soirée', 'crédible', 'farfelue'],
  ['Un mensonge', 'tout petit', 'énorme'],
  ['Une bêtise d\'enfant', 'mignonne', 'impardonnable'],
  ['Un défaut', 'léger', 'rédhibitoire'],
  ['Une qualité', 'secondaire', 'essentielle'],
  ['Un moment de la journée', 'qu\'on déteste', 'qu\'on adore'],
  ['Un jour de la semaine', 'qu\'on déteste', 'qu\'on adore'],
  ['Une saison', 'peu appréciée', 'adorée'],
  ['Un bruit', 'agréable', 'insupportable'],
  ['Une odeur', 'agréable', 'répugnante'],
  ['Un goût', 'agréable', 'immonde'],
  ['Un son de la nature', 'apaisant', 'effrayant'],
  ['Une couleur', 'qu\'on aime', 'qu\'on déteste'],
  ['Une série', 'nulle', 'culte'],
  ['Un jeu vidéo', 'mauvais', 'légendaire'],
  ['Un jeu de société', 'sans intérêt', 'incontournable'],
  ['Un jeu de société', 'rapide', 'interminable'],
  ['Une chanson', 'ringarde', 'hymne absolu'],
  ['Un chanteur ou une chanteuse', 'mauvais', 'génial'],
  ['Un instrument de musique', 'discret', 'assourdissant'],
  ['Un genre musical', 'qu\'on évite', 'qu\'on adore'],
  ['Un objet à emmener sur une île déserte', 'inutile', 'vital'],
  ['Un objet à emmener en randonnée', 'superflu', 'indispensable'],
  ['Un truc à mettre dans une valise', 'inutile', 'indispensable'],
  ['Un truc à faire avant de mourir', 'banal', 'incroyable'],
  ['Un truc à faire en solo', 'ennuyeux', 'passionnant'],
  ['Un vêtement', 'confortable', 'inconfortable'],
  ['Un vêtement', 'discret', 'excentrique'],
  ['Un accessoire', 'banal', 'extravagant'],
  ['Une coupe de cheveux', 'sage', 'complètement folle'],
  ['Un talent caché', 'inutile', 'impressionnant'],
  ['Un défi', 'facile', 'impossible'],
  ['Un défi de soirée', 'gentil', 'extrême'],
  ['Un gage', 'gentil', 'humiliant'],
  ['Une fête', 'calme', 'démesurée'],
  ['Un événement', 'banal', 'historique'],
  ['Un événement de la vie', 'léger', 'majeur'],
  ['Une tradition de Noël', 'ringarde', 'magique'],
  ['Un cadeau de Noël', 'décevant', 'le meilleur de tous'],
  ['Un jouet', 'ennuyeux', 'qu\'on s\'arrache'],
  ['Un truc qu\'on trouve dans un frigo', 'périmé', 'délicieux'],
  ['Un truc qu\'on trouve dans une trousse', 'peu utile', 'essentiel'],
  ['Un truc qu\'on trouve dans une salle de bain', 'banal', 'luxueux'],
  ['Un truc qu\'on trouve dans un sac', 'léger', 'lourd'],
  ['Un truc qu\'on oublie', 'sans conséquence', 'catastrophe'],
  ['Un truc qui fait perdre du temps', 'quelques secondes', 'des heures'],
  ['Un truc qui rend heureux', 'petit bonheur', 'immense joie'],
  ['Une mauvaise nouvelle', 'petite', 'catastrophique'],
  ['Une bonne nouvelle', 'sympa', 'incroyable'],
  ['Une dispute', 'anodine', 'grave'],
  ['Une punition', 'légère', 'sévère'],
  ['Une matière scolaire', 'adorée', 'détestée'],
  ['Un bruit dans la nuit', 'rassurant', 'terrifiant'],
  ['Un lieu hanté', 'rigolo', 'terrifiant'],
  ['Un monstre', 'ridicule', 'terrifiant'],
  ['Un personnage historique', 'méconnu', 'célèbre'],
  ['Une célébrité', 'peu connue', 'mondialement connue'],
  ['Un youtubeur ou une youtubeuse', 'débutant', 'superstar'],
  ['Une application', 'inutile', 'indispensable'],
  ['Un réseau social', 'ennuyeux', 'addictif'],
  ['Une invention', 'inutile', 'révolutionnaire'],
  ['Un bâtiment', 'petit', 'gigantesque'],
  ['Un monument', 'discret', 'mythique'],
  ['Un sommet à gravir', 'facile', 'extrême'],
  ['Un fruit', 'acide', 'sucré'],
  ['Un légume', 'qu\'on déteste', 'qu\'on adore'],
  ['Un dessert', 'léger', 'hyper calorique'],
  ['Un fromage', 'doux', 'qui pue'],
  ['Une marque', 'discount', 'luxe'],
  ['Une voiture', 'poubelle', 'de rêve'],
  ['Un voisin', 'sympa', 'insupportable'],
  ['Un collègue', 'adorable', 'cauchemar'],
  ['Un type de personne en soirée', 'discret', 'envahissant'],
  ['Un défaut en soirée', 'sans gravité', 'qui gâche tout'],
  ['Une question gênante', 'banale', 'très gênante'],
  ['Un secret', 'anodin', 'explosif'],
  ['Un souvenir d\'enfance', 'oublié', 'inoubliable'],
  ['Un cauchemar', 'léger', 'horrible'],
  ['Un rêve', 'banal', 'extraordinaire'],
  ['Une chance', 'petite', 'incroyable'],
  ['Un risque', 'minuscule', 'énorme'],
  ['Une dépense', 'minuscule', 'ruineuse'],
  ['Une chose qui prend du temps', 'quelques secondes', 'des années'],
];

const THEMES: TenTheme[] = CARDS.map(([t, lo, hi]) => ({ t, lo, hi }));

// Trois thèmes au hasard, sans répéter ceux déjà joués
const pickThemes = (used: string[], n = 3): TenTheme[] => {
  const key = (x: TenTheme) => `${x.t}|${x.lo}|${x.hi}`;
  const pool = THEMES.filter((x) => !used.includes(key(x)));
  const bag = [...(pool.length >= n ? pool : THEMES)];
  const out: TenTheme[] = [];
  while (out.length < n && bag.length) out.push(bag.splice(Math.floor(Math.random() * bag.length), 1)[0]);
  return out;
};
const themeKey = (x: TenTheme) => `${x.t}|${x.lo}|${x.hi}`;

export { THEMES, pickThemes, themeKey };
